# Generated by Django 3.2.4 on 2021-07-01 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='follows',
        ),
        migrations.RemoveField(
            model_name='following',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='story',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='list',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='owner',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
        migrations.DeleteModel(
            name='Following',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
        migrations.DeleteModel(
            name='TimeLine',
        ),
    ]
