# Generated by Django 3.2.4 on 2021-07-02 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bros', '0010_auto_20210701_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='body',
            new_name='story_body',
        ),
    ]
